name: Build MSI Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x gradlew

    - name: Build the project and create MSI
      run: |
        ./gradlew clean build
        ./gradlew jpackage --verbose

    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v3
      with:
        name: gamesense-installer
        path: build/jpackage/*.msi
